# backend/app/services/seed_classes.py

CLASS_STRUCTURE = {
    "kg": [
        {"name": "KG 1A", "capacity": 15},
        {"name": "KG 1B", "capacity": 15},
        {"name": "KG 2A", "capacity": 15},
        {"name": "KG 2B", "capacity": 15},
    ],
    "nursery": [
        {"name": "NUR 1A", "capacity": 20},
        {"name": "NUR 1B", "capacity": 20},
        {"name": "NUR 2A", "capacity": 20},
        {"name": "NUR 2B", "capacity": 20},
    ],
    "primary": [
        {"name": "PRY 1A", "capacity": 25},
        {"name": "PRY 1B", "capacity": 25},
        {"name": "PRY 1C", "capacity": 25},
        {"name": "PRY 2A", "capacity": 25},
        {"name": "PRY 2B", "capacity": 25},
        {"name": "PRY 2C", "capacity": 25},
        {"name": "PRY 3A", "capacity": 25},
        {"name": "PRY 3B", "capacity": 25},
        {"name": "PRY 3C", "capacity": 25},
        {"name": "PRY 4A", "capacity": 25},
        {"name": "PRY 4B", "capacity": 25},
        {"name": "PRY 4C", "capacity": 25},
        {"name": "PRY 5A", "capacity": 25},
        {"name": "PRY 5B", "capacity": 25},
        {"name": "PRY 5C", "capacity": 25},
    ],
    "jss": [
        {"name": "JSS 1A", "capacity": 30},
        {"name": "JSS 1B", "capacity": 30},
        {"name": "JSS 1C", "capacity": 30},
        {"name": "JSS 1D", "capacity": 30},
        {"name": "JSS 2A", "capacity": 30},
        {"name": "JSS 2B", "capacity": 30},
        {"name": "JSS 2C", "capacity": 30},
        {"name": "JSS 2D", "capacity": 30},
        {"name": "JSS 3A", "capacity": 30},
        {"name": "JSS 3B", "capacity": 30},
        {"name": "JSS 3C", "capacity": 30},
        {"name": "JSS 3D", "capacity": 30},
    ],
    "sss": [
        {"name": "SSS 1A", "capacity": 30, "stream": "science"},
        {"name": "SSS 1B", "capacity": 30, "stream": "technical"},
        {"name": "SSS 1C", "capacity": 30, "stream": "commercial"},
        {"name": "SSS 1D", "capacity": 30, "stream": "arts"},
        {"name": "SSS 2A", "capacity": 30, "stream": "science"},
        {"name": "SSS 2B", "capacity": 30, "stream": "technical"},
        {"name": "SSS 2C", "capacity": 30, "stream": "commercial"},
        {"name": "SSS 2D", "capacity": 30, "stream": "arts"},
        {"name": "SSS 3A", "capacity": 30, "stream": "science"},
        {"name": "SSS 3B", "capacity": 30, "stream": "technical"},
        {"name": "SSS 3C", "capacity": 30, "stream": "commercial"},
        {"name": "SSS 3D", "capacity": 30, "stream": "arts"},
    ],
}
